export DOTFILES="$HOME/.dotfiles"
export GOPATH="$HOME/.go"
export DENO_NO_UPDATE_CHECK="1"

export PATH="/opt/homebrew/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
export PATH="$DOTFILES/.config/bin:$PATH"
