export ZSH="$HOME/.oh-my-zsh"
export DOTFILES="$HOME/.dotfiles"
export GOPATH="$HOME/.go"

export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"

alias touch-bar-reset="killall ControlStrip"
alias serve="servor --reload"

ZSH_DISABLE_COMPFIX=true
ZSH_THEME="robbyrussell"

plugins=(git)

source "$ZSH/oh-my-zsh.sh"
