export ZSH="$HOME/.oh-my-zsh"
export DOTFILES="$HOME/.dotfiles"
export PATH="$HOME/.cargo/bin:$PATH"

alias touch-bar-reset="killall ControlStrip"
alias serve="servor --reload"

ZSH_THEME="robbyrussell"

plugins=(git)

source "$ZSH/oh-my-zsh.sh"
